"use client";
import {useMemo,useRef,useState} from "react";

export type GeoFeature={type?:"Feature";geometry:{type:"Point"|"MultiPoint"|"LineString"|"MultiLineString"|"Polygon"|"MultiPolygon";coordinates:any};properties:Record<string,any>;id?:string|number};
export type GeoCollection={type:"FeatureCollection";features:GeoFeature[]};
export type LayerStyle={color:string;fill?:string;width?:number;pointRadius?:number;opacity?:number};
export type VizMode="simple"|"cluster"|"heat"|"draw";
export type DrawPolygon={type:"Polygon";coordinates:number[][][]};
const W=900,H=600,TILE=256;
function world(lon:number,lat:number,z:number){const s=TILE*2**z,sin=Math.sin(lat*Math.PI/180);return{x:((lon+180)/360)*s,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*s}}
function unworld(x:number,y:number,z:number){const s=TILE*2**z,lon=x/s*360-180,n=Math.PI-2*Math.PI*y/s,lat=180/Math.PI*Math.atan(.5*(Math.exp(n)-Math.exp(-n)));return[lon,lat]}
function project(p:number[],z:number,cx:number,cy:number){const q=world(p[0],p[1],z);return[q.x-cx+W/2,q.y-cy+H/2]}
function polygonPath(f:GeoFeature,z:number,cx:number,cy:number){const polys=f.geometry.type==="Polygon"?[f.geometry.coordinates]:f.geometry.coordinates;return polys.map((poly:number[][][])=>poly.map((ring:number[][])=>ring.map((p,i)=>{const[x,y]=project(p,z,cx,cy);return`${i?"L":"M"}${x.toFixed(1)} ${y.toFixed(1)}`}).join("")+"Z").join(" ")).join(" ")}
function linePath(f:GeoFeature,z:number,cx:number,cy:number){const lines=f.geometry.type==="LineString"?[f.geometry.coordinates]:f.geometry.coordinates;return lines.map((line:number[][])=>line.map((p,i)=>{const[x,y]=project(p,z,cx,cy);return`${i?"L":"M"}${x.toFixed(1)} ${y.toFixed(1)}`}).join("")).join(" ")}
function featureName(f:GeoFeature){const p=f.properties||{};return String(p.NOMBRE??p.NOM_BARRIO??p.NOM_TERR??p.BARRIO??p.TERRITORIO??p.COD_MZN??p.cod_mzn??p.EXPROP_ID??"Elemento")}
function meters(a:number[],b:number[]){const k=Math.PI/180,x=(b[0]-a[0])*k*Math.cos((a[1]+b[1])*k/2),y=(b[1]-a[1])*k;return Math.hypot(x,y)*6371008.8}
function lineArrays(f:GeoFeature){return(f.geometry.type==="LineString"?[f.geometry.coordinates]:f.geometry.coordinates) as number[][][]}
function heapPush(h:[number,string][],v:[number,string]){h.push(v);let i=h.length-1;while(i){const p=(i-1)>>1;if(h[p][0]<=v[0])break;h[i]=h[p];i=p}h[i]=v}
function heapPop(h:[number,string][]):[number,string]|null{if(!h.length)return null;const root=h[0],last=h.pop()!;if(h.length){let i=0;while(true){let c=i*2+1;if(c>=h.length)break;if(c+1<h.length&&h[c+1][0]<h[c][0])c++;if(h[c][0]>=last[0])break;h[i]=h[c];i=c}h[i]=last}return root}

export default function InteractiveMap({data,active,styles,onFeature,viz="simple",selectedLayerId,onPolygon,streets,analysis="Cantidad de registros",selectedFeature,selectedFeatures=[],isoMode="A pie",isoMinutes=10,radius=500}:{data:Record<string,GeoCollection>;active:string[];styles:Record<string,LayerStyle>;onFeature:(f:GeoFeature,layerId:string)=>void;viz?:VizMode;selectedLayerId?:string;onPolygon?:(p:DrawPolygon|null)=>void;streets?:GeoCollection;analysis?:string;selectedFeature?:GeoFeature|null;selectedFeatures?:GeoFeature[];isoMode?:string;isoMinutes?:number;radius?:number}){
 const[center,setCenter]=useState({lon:-70.657,lat:-33.448});const[zoom,setZoom]=useState(14);const[draw,setDraw]=useState<number[][]>([]);const drag=useRef<{x:number;y:number;center:{lon:number;lat:number}}|null>(null);const drawing=useRef(false);const cw=world(center.lon,center.lat,zoom);
 const tiles=useMemo(()=>{const minX=Math.floor((cw.x-W/2)/TILE),maxX=Math.floor((cw.x+W/2)/TILE),minY=Math.floor((cw.y-H/2)/TILE),maxY=Math.floor((cw.y+H/2)/TILE),n=2**zoom,out:{x:number;y:number;tx:number;ty:number}[]=[];for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)if(y>=0&&y<n)out.push({x,y,tx:x*TILE-cw.x+W/2,ty:y*TILE-cw.y+H/2});return out},[cw.x,cw.y,zoom]);
 const selectedPoints=useMemo(()=>{const fc=selectedLayerId?data[selectedLayerId]:undefined;if(!fc)return[];return fc.features.filter(f=>f.geometry.type==="Point").map((f,i)=>{const[x,y]=project(f.geometry.coordinates,zoom,cw.x,cw.y);return{x,y,f,i}})},[data,selectedLayerId,zoom,cw.x,cw.y]);
 const clusters=useMemo(()=>{const out:{x:number;y:number;items:typeof selectedPoints}[]=[];selectedPoints.forEach(p=>{const h=out.find(c=>Math.hypot(c.x-p.x,c.y-p.y)<38);if(h){h.items.push(p);h.x=h.items.reduce((a,v)=>a+v.x,0)/h.items.length;h.y=h.items.reduce((a,v)=>a+v.y,0)/h.items.length}else out.push({x:p.x,y:p.y,items:[p]})});return out},[selectedPoints]);
 const anchor=useMemo(()=>{if(selectedFeature?.geometry.type==="Point")return selectedFeature;return selectedPoints[0]?.f??null},[selectedFeature,selectedPoints]);
 const isoPolygon=useMemo(()=>{const sf=streets?.features??[];if(analysis!=="Isócronas"||!anchor||!sf.length)return"";const origin=anchor.geometry.coordinates as number[],max=(isoMode==="Vehículo"?8.33:isoMode==="Bicicleta"?4.2:1.4)*isoMinutes*60,nodes=new Map<string,number[]>(),edges=new Map<string,{to:string;cost:number}[]>(),key=(p:number[])=>`${p[0].toFixed(5)},${p[1].toFixed(5)}`;sf.filter(f=>f.geometry.type==="LineString"||f.geometry.type==="MultiLineString").forEach(f=>lineArrays(f).forEach(line=>{for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i],ka=key(a),kb=key(b),cost=meters(a,b);nodes.set(ka,a);nodes.set(kb,b);edges.set(ka,[...(edges.get(ka)||[]),{to:kb,cost}]);edges.set(kb,[...(edges.get(kb)||[]),{to:ka,cost}])}}));if(!nodes.size)return"";let start="",best=Infinity;nodes.forEach((p,k)=>{const d=meters(origin,p);if(d<best){best=d;start=k}});const dist=new Map<string,number>([[start,0]]),queue:[number,string][]=[[0,start]],reached:number[][]=[];while(queue.length){const item=heapPop(queue);if(!item)break;const[d,k]=item;if(d!==(dist.get(k)??Infinity)||d>max)continue;const node=nodes.get(k);if(node)reached.push(node);for(const e of edges.get(k)||[]){const nd=d+e.cost;if(nd<=max&&nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);heapPush(queue,[nd,e.to])}}}const bins=new Map<number,{p:number[];d:number}>();reached.forEach(p=>{const a=Math.atan2(p[1]-origin[1],(p[0]-origin[0])*Math.cos(origin[1]*Math.PI/180)),bin=Math.round((a+Math.PI)*36/Math.PI)%72,d=meters(origin,p),old=bins.get(bin);if(!old||d>old.d)bins.set(bin,{p,d})});return[...bins.entries()].sort((a,b)=>a[0]-b[0]).map(([,v])=>{const q=world(v.p[0],v.p[1],zoom);return`${(q.x-cw.x+W/2).toFixed(1)},${(q.y-cw.y+H/2).toFixed(1)}`}).join(" ")},[analysis,anchor,streets,isoMode,isoMinutes,zoom,cw.x,cw.y]);
 const radiusPx=useMemo(()=>radius/(Math.cos(center.lat*Math.PI/180)*2*Math.PI*6378137/(TILE*2**zoom)),[radius,center.lat,zoom]);
 const screen=(e:React.PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();return[(e.clientX-r.left)/r.width*W,(e.clientY-r.top)/r.height*H]};
 const screenToLonLat=(p:number[])=>unworld(p[0]+cw.x-W/2,p[1]+cw.y-H/2,zoom);
 const move=(e:React.PointerEvent)=>{if(drawing.current){const p=screen(e);setDraw(a=>a.length&&Math.hypot(a[a.length-1][0]-p[0],a[a.length-1][1]-p[1])<5?a:[...a,p]);return}if(!drag.current)return;const scale=TILE*2**zoom,dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y,c=world(drag.current.center.lon,drag.current.center.lat,zoom),x=c.x-dx,y=c.y-dy,lon=x/scale*360-180,n=Math.PI-2*Math.PI*y/scale,lat=180/Math.PI*Math.atan(.5*(Math.exp(n)-Math.exp(-n)));setCenter({lon,lat})};
 const finish=()=>{if(drawing.current){drawing.current=false;if(draw.length>=3){const ring=draw.map(screenToLonLat);ring.push([...ring[0]]);onPolygon?.({type:"Polygon",coordinates:[ring]})}else onPolygon?.(null)}drag.current=null};
 return <div className="interactiveMap" onWheel={e=>{e.preventDefault();setZoom(z=>Math.max(11,Math.min(18,z+(e.deltaY<0?1:-1))))}} onPointerDown={e=>{if((e.target as Element).closest(".zoomControl"))return;if(viz==="draw"){drawing.current=true;setDraw([screen(e)]);onPolygon?.(null)}else drag.current={x:e.clientX,y:e.clientY,center};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={move} onPointerUp={finish}>
  <svg viewBox={`0 0 ${W} ${H}`}>
   <defs><radialGradient id="heatGrad"><stop offset="0%" stopColor="#e63b2e" stopOpacity=".48"/><stop offset="45%" stopColor="#f29c38" stopOpacity=".24"/><stop offset="100%" stopColor="#f6d55c" stopOpacity="0"/></radialGradient></defs>
   <g className="osmTiles">{tiles.map(t=><image key={`${zoom}-${t.x}-${t.y}`} href={`https://tile.openstreetmap.org/${zoom}/${((t.x%2**zoom)+2**zoom)%2**zoom}/${t.y}.png`} x={t.tx} y={t.ty} width={TILE} height={TILE}/>)}</g>
   {active.map(id=>{const fc=data[id],s=styles[id]||{color:"#333"};if(!fc)return null;const hideSelectedPoints=id===selectedLayerId&&(viz==="cluster"||viz==="heat");return <g key={id} data-layer={id}>{fc.features.map((f,i)=>{const common={key:i,onClick:(e:any)=>{e.stopPropagation();onFeature(f,id)}};if(f.geometry.type==="Point"){if(hideSelectedPoints)return null;const[x,y]=project(f.geometry.coordinates,zoom,cw.x,cw.y);return <circle {...common} cx={x} cy={y} r={s.pointRadius??5} fill={s.color} fillOpacity={s.opacity??.9} stroke="#fff" strokeWidth="1.2"><title>{featureName(f)}</title></circle>}if(f.geometry.type==="MultiPoint")return <g key={i}>{f.geometry.coordinates.map((p:number[],j:number)=>{const[x,y]=project(p,zoom,cw.x,cw.y);return <circle key={j} cx={x} cy={y} r={s.pointRadius??4} fill={s.color}/>})}</g>;if(f.geometry.type==="LineString"||f.geometry.type==="MultiLineString")return <path {...common} d={linePath(f,zoom,cw.x,cw.y)} fill="none" stroke={s.color} strokeWidth={s.width??1.5} strokeOpacity={s.opacity??.9} vectorEffect="non-scaling-stroke"><title>{featureName(f)}</title></path>;return <path {...common} d={polygonPath(f,zoom,cw.x,cw.y)} fill={s.fill??s.color} fillOpacity={s.opacity??.08} stroke={s.color} strokeWidth={s.width??1} vectorEffect="non-scaling-stroke"><title>{featureName(f)}</title></path>})}</g>})}
   {analysis==="Buffer desde punto"&&anchor&&(()=>{const[x,y]=project(anchor.geometry.coordinates,zoom,cw.x,cw.y);return <circle cx={x} cy={y} r={radiusPx} fill="#0b4a8b" fillOpacity=".08" stroke="#0b4a8b" strokeWidth="1.5" strokeDasharray="5 4"/>})()}
   {isoPolygon&&<polygon points={isoPolygon} fill="#0b4a8b" fillOpacity=".16" stroke="#0b4a8b" strokeWidth="2" strokeDasharray="6 4"/>}
   {viz==="heat"&&selectedPoints.map((p,i)=><circle key={`h${i}`} cx={p.x} cy={p.y} r="38" fill="url(#heatGrad)"/>)}
   {viz==="cluster"&&clusters.map((c,i)=><g key={`c${i}`} onClick={()=>c.items[0]&&onFeature(c.items[0].f,selectedLayerId||"")}><circle cx={c.x} cy={c.y} r={Math.min(24,9+Math.sqrt(c.items.length)*3)} fill="#073879" fillOpacity=".9" stroke="#fff" strokeWidth="2"/><text x={c.x} y={c.y+3} textAnchor="middle" fontSize="10" fill="#fff" fontWeight="700">{c.items.length}</text></g>)}
   {selectedFeatures.filter(f=>f.geometry.type==="Point").map((f,i)=>{const[x,y]=project(f.geometry.coordinates,zoom,cw.x,cw.y);return <circle key={`sel${i}`} cx={x} cy={y} r="8" fill="none" stroke="#ffbd00" strokeWidth="3"/>})}
   {draw.length>1&&<polygon points={draw.map(p=>p.join(",")).join(" ")} fill="#ffbd00" fillOpacity=".14" stroke="#073879" strokeWidth="2" strokeDasharray="5 4"/>}
  </svg>
  <div className="zoomControl"><button onClick={()=>setZoom(z=>Math.min(18,z+1))}>+</button><b>{zoom}</b><button onClick={()=>setZoom(z=>Math.max(11,z-1))}>−</button></div>
  <div className="mapAttribution">© OpenStreetMap contributors · fondo gris</div>
 </div>
}
